driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-5.11
  - name: centos-6.7
  - name: centos-7.1
  - name: debian-7.8
    run_list: apt::default
  - name: debian-8.2
    run_list: apt::default
  - name: fedora-22
  - name: fedora-23
  - name: freebsd-9.3
  - name: freebsd-10.2
  - name: opensuse-13.2
  - name: ubuntu-12.04
    run_list: apt::default
  - name: ubuntu-14.04
    run_list: apt::default
  - name: ubuntu-15.10
    run_list: apt::default

suites:
  - name: default
    run_list:
      - recipe[ntp::default]
    attributes:
      ntp:
        sync_clock: true
        sync_hw_clock: true
  - name: undo
    run_list:
      - recipe[ntp::undo]
